Repository WanderAR-app/server, pull requests merged in 2023-06, with the labels that each got.

#3 Auth
  .env.example
  db/.sql
  package-lock.json
  package.json
  src/app.ts
  src/database/mariadb.ts
  src/middlewares/CheckJWT.ts
  src/routes/auth/auth.ts
  src/types/User.ts
Labels: Approved

#6 Env variables example
  .env.example
Labels: Waiting review

#5 GitHub actions workflow
  .github/workflows/dev_build.yml
  .github/workflows/main_test_release.yml
Labels: Waiting review

#7 Final merge before Delivery
  .env.example
  .github/workflows/dev_build.yml
  .github/workflows/main_test_release.yml
  db/.sql
  package-lock.json
  package.json
  src/app.ts
  src/database/mariadb.ts
  src/middlewares/CheckJWT.ts
  src/routes/auth/admin.ts
  src/routes/auth/auth.ts
  src/types/Admin.ts
  src/types/User.ts
Labels: Approved, Waiting review

#8 Google auth
  db/.sql
  package-lock.json
  package.json
  src/app.ts
  src/routes/auth/google.ts
  src/routes/auth/googleAuth.ts
  src/types/User.ts
  src/utils/generateJWT.ts
Labels: Approved

#10 [UP] - Correct stupid inequality error
  .github/workflows/main_test_release.yml
Labels: Waiting review

#12 Revert "Final merge before Delivery"
  .env.example
  .github/workflows/dev_build.yml
  .github/workflows/main_test_release.yml
  db/.sql
  package-lock.json
  package.json
  src/app.ts
  src/database/mariadb.ts
  src/middlewares/CheckJWT.ts
  src/routes/auth/admin.ts
  src/routes/auth/auth.ts
  src/types/Admin.ts
  src/types/User.ts
Labels: Approved
